@PlaylistControl_HostAddress = http://localhost:5137

GET {{PlaylistControl_HostAddress}}/weatherforecast/
Accept: application/json

### Inserting users
POST {{PlaylistControl_HostAddress}}/user/
Content-Type: application/json

{
    "Name": "User 3"
}

### Updating users
PUT {{PlaylistControl_HostAddress}}/user/3/
Content-Type: application/json

{
    "Name": "Wagdi"
}

### Getting users
GET {{PlaylistControl_HostAddress}}/user/
Accept: application/json

### Deleting users
DELETE {{PlaylistControl_HostAddress}}/user/2/
Accept: application/json

### Creating playlists
POST {{PlaylistControl_HostAddress}}/user/3/playlists/
Content-Type: application/json

{
    "Name": "Playlist 4",
    "Description": "Description 4"
}

### Updating playlist info
PUT {{PlaylistControl_HostAddress}}/user/3/playlists/4/
Content-Type: application/json

{
    "Description": "Goodness"
}

### Adding playlist
POST {{PlaylistControl_HostAddress}}/user/3/playlists/3/
Accept: application/json

### Getting user playlists
GET {{PlaylistControl_HostAddress}}/user/3/playlists/
Accept: application/json

### Removing user playlists
DELETE {{PlaylistControl_HostAddress}}/user/1/playlists/2/
Accept: application/json

### Adding songs
POST {{PlaylistControl_HostAddress}}/song/
Content-Type: application/json

{
    "Title": "Title 2",
    "Artist": "Artist 2",
    "Album": "Album 2",
    "Year": 2026,
    "Genre": "Genre 2"
}

### Updating songs
PUT {{PlaylistControl_HostAddress}}/song/3/
Content-Type: application/json

{
    "Genre": "Quirky"
}

### Getting songs
GET {{PlaylistControl_HostAddress}}/song/
Accept: application/json

### Getting song details
GET {{PlaylistControl_HostAddress}}/song/1/details/
Accept: application/json

### Delete song
DELETE  {{PlaylistControl_HostAddress}}/song/1
Accept: application/json

### Add song to playlist
POST {{PlaylistControl_HostAddress}}/user/2/songs/2/addToPlaylist/3/

### Getting songs in playlist
GET {{PlaylistControl_HostAddress}}/playlist/3/songs/
Accept: application/json

### Remove song from playlist
DELETE {{PlaylistControl_HostAddress}}/user/2/playlists/3/RemoveFromPlaylist/1/
Accept: application/json

### Getting playlists
GET {{PlaylistControl_HostAddress}}/playlist/
Accept: application/json

### Getting playlists by id
GET {{PlaylistControl_HostAddress}}/playlist/3/
Accept: application/json